### ISSUE TITLE
Placeholder links aren't rendered properly

### ISSUE THREAD

**Issue by elazar** [phergie/phergie.org#9]
<img width="747" alt="_phergie_-_a_php_irc_bot_ _phergie_is_an_open_source_irc_bot_written_in_php_5" src="https://cloud.githubusercontent.com/assets/15487/10741820/b40e8e18-7bf7-11e5-9fef-5794fd996d4e.png">

**Comment by svpernova09** [comment]
Fixed in e3815439668dbf297a0685fe7839124a91768977
